# byctrl配置文件，需要放在调用进程或byctrl.dll同目录，调用进程一般情况下为主程序，文件编码utf-8
# 井号开头的行为注释，没有井号的内容若想更改可以直接改等号后面的数字，每一个配置前面都有一个代井号的说明，告诉你接下来的值是做什么用的。

# 是否使用独立通道朗读，0读屏通道，1独立通道
speak.useSlave = 0

# 朗读通道名称，仅独立通道生效
# 为空则使用共享三方通道，通道不存在会自动创建
speak.slaveName = 游戏

# 是否始终排队朗读，该参数不存在时由开发者决定是否排队朗读，0始终排队朗读，除非手动打断，1始终打断朗读
# speak.append = 1

# 朗读时是否允许被打断，0不允许打断，，1允许打断
speak.allowBreak = 1

# 是否启用任意键打断，0按下厨读屏设置的打断剑以外都不打断朗读，1按下任何按键都打断朗读
anyKeyBreak = 1

# 日志文件路径，存放日志文件的路径，开发者的参数优先
logPath =